import "ResourceCandidate.idl";

namespace MrmLib
{
    runtimeclass ReplacePathCandidatesWithEmbeddedDataResult
    {
        [interface_name("IReplacePathCandidatesWithEmbeddedDataResult", E4E95D99-E242-44AB-8AF8-9CCCC5C4FBF1)]
        {
            IVectorView<ResourceCandidate> CandidatesReplaced { get; };
        }
    }

    enum PriType
    {
        Unknown = -1,
        WindowsEight,
        WindowsBlue,
        WindowsPhoneBlue,
        Universal,
        UniversalRS4,
        UniversalVNext,
        Test
    };

    struct PriVersion
    {
        UInt16 Major;
        UInt16 Minor;
    };

    runtimeclass PriFile
    {
        [static_name("IPriFileStatics", CE68A109-67EE-4B84-8823-32413732A4F3)]
        {
            [default_overload]
            static Windows.Foundation.IAsyncOperation<PriFile> LoadAsync(UInt8[] priBytes);

            [method_name("LoadAsyncWithPath")]
            static Windows.Foundation.IAsyncOperation<PriFile> LoadAsync(String priFilePath);

            [method_name("LoadAsyncWithStorageFile")]
            static Windows.Foundation.IAsyncOperation<PriFile> LoadAsync(Windows.Storage.StorageFile priFile);
        }

        [interface_name("IPriFile", B2C08FB5-B44A-4A5D-83C0-EF07945C9CAC)]
        {
            IVector<ResourceCandidate> ResourceCandidates { get; };

            [default_overload]
            Windows.Foundation.IAsyncOperation<ReplacePathCandidatesWithEmbeddedDataResult>
                ReplacePathCandidatesWithEmbeddedDataAsync(Windows.Storage.StorageFolder sourceFolderToEmbed);

            [method_name("ReplacePathCandidatesWithEmbeddedDataAsyncWithPath")]
            Windows.Foundation.IAsyncOperation<ReplacePathCandidatesWithEmbeddedDataResult>
                ReplacePathCandidatesWithEmbeddedDataAsync(String sourceFolderPathToEmbed);

            UInt8[] Write();
            [method_name("WriteAsyncWithPath")]
            Windows.Foundation.IAsyncAction WriteAsync(String destinationFilePath);
            [default_overload]
            Windows.Foundation.IAsyncAction WriteAsync(Windows.Storage.StorageFile destinationFile);
            [method_name("WriteAsyncWithStream")]
            Windows.Foundation.IAsyncAction WriteAsync(Windows.Storage.Streams.IOutputStream destinationStream);
        }

        [interface_name("IPriFile2", FA4F333B-B52F-405C-A614-016C1BC68F89)]
        {
            // Magic
            PriType Type { get; };
            UInt64 Magic { get; };
            String MagicString { get; };

            // Version
            PriVersion Version { get; };
            UInt32 Checksum { get; };

            // Identifiers
            String SimpleId { get; set; };
            String UniqueId { get; set; };
        }

        [interface_name("IPriFile3", ED6A289B-F609-4972-B2C2-2CD3CC5CCCF6)]
        {
			Windows.Storage.Streams.IBuffer WriteAsBuffer();
            Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer> WriteAsBufferAsync();

            [method_name("WriteAsyncWithBuffer")]
            Windows.Foundation.IAsyncAction WriteAsync(Windows.Storage.Streams.IBuffer destinationBuffer);
        }
    }
}