namespace MrmLib
{
    enum QualifierAttribute
    {
        Language = 0,
        Contrast = 1,
        Scale = 2,
        HomeRegion = 3,
        TargetSize = 4,
        LayoutDirection = 5,
        Theme = 6,
        AlternateForm = 7,
        DXFeatureLevel = 8,
        Configuration = 9,
        DeviceFamily = 10,
        Custom = 11
    };

    enum QualifierOperator
    {
        False = 0,
        True = 1,
        AttributeDefined = 2,
        AttributeUndefined = 3,
        NotEqual = 4,
        NoMatch = 5,
        Less = 6,
        LessOrEqual = 7,
        Greater = 8,
        GreaterOrEqual = 9,
        Match = 10,
        Equal = 11,
        ExtendedOperator = 12,
        Custom = 13
    };

    runtimeclass Qualifier
    {
        [static_name("IQualifierStatics", B8ADFE39-1159-4EAF-8BFE-E6DA5BB4C55F)]
        {
            static Qualifier Create(QualifierAttribute qualifierAttribute, QualifierOperator qualifierOperator, String qualifierValue, Int32 priority, Double fallbackScore);
            [default_overload]
            static Qualifier Create(QualifierAttribute qualifierAttribute, QualifierOperator qualifierOperator, String qualifierValue, Double fallbackScore);
            [default_overload]
            static Qualifier Create(QualifierAttribute qualifierAttribute, QualifierOperator qualifierOperator, String qualifierValue);
            [method_name("CreateQualifierWithMatchOperator")]
            static Qualifier Create(QualifierAttribute qualifierAttribute, String qualifierValue, Int32 priority, Double fallbackScore);
            [method_name("CreateQualifierWithMatchOperatorAndDefaultPriority")]
            static Qualifier Create(QualifierAttribute qualifierAttribute, String qualifierValue, Double fallbackScore);
            static Qualifier Create(QualifierAttribute qualifierAttribute, String qualifierValue);
        }

        [interface_name("IQualifier", D22E530A-5BB0-4F27-A2BF-2B0A3D6A941A)]
        {
            QualifierAttribute Attribute { get; };
            String AttributeName { get; };
            QualifierOperator Operator { get; };
            String CustomOperator { get; };
            String Value { get; };
            Int32 Priority { get; };
            Double FallbackScore { get; };
        }
    };
}