import "Qualifier.idl";

namespace MrmLib
{
    enum ResourceValueType
    {
        String,
        Path,
        EmbeddedData
    };

    runtimeclass ResourceCandidate
    {
        [static_name("IResourceCandidateStatics", 3B673525-80B9-48D7-B959-DDEE14C2DDE1)]
        {
            [default_overload]
            static ResourceCandidate Create(String resourceName, ResourceValueType valueType, String stringValue);
            [method_name("CreateResourceCandidateWithQualifiers")]
            static ResourceCandidate Create(String resourceName, ResourceValueType valueType, String stringValue, Qualifier[] qualifiers);
            [method_name("CreateDataResourceCandidate")]
            static ResourceCandidate Create(String resourceName, UInt8[] dataValue);
            [method_name("CreateDataResourceCandidateWithQualifiers")]
            static ResourceCandidate Create(String resourceName, UInt8[] dataValue, Qualifier[] qualifiers);
        }

        [static_name("IResourceCandidateStatics2", 546EA32E-5BA2-4A06-8733-BDE1511A39D7)]
        {
            [method_name("CreateResourceCandidateWithQualifiersView")]
            static ResourceCandidate Create(String resourceName, ResourceValueType valueType, String stringValue, IVectorView<Qualifier> qualifiers);
            [default_overload]
            [method_name("CreateDataResourceCandidateWithQualifiersView")]
            static ResourceCandidate Create(String resourceName, UInt8[] dataValue, IVectorView<Qualifier> qualifiers);
            [method_name("CreateDataBufferResourceCandidate")]
            static ResourceCandidate Create(String resourceName, Windows.Storage.Streams.IBuffer dataValue);
            [method_name("CreateDataBufferResourceCandidateWithQualifiers")]
            static ResourceCandidate Create(String resourceName, Windows.Storage.Streams.IBuffer dataValue, Qualifier[] qualifiers);
            [method_name("CreateDataBufferResourceCandidateWithQualifiersView")]
            static ResourceCandidate Create(String resourceName, Windows.Storage.Streams.IBuffer dataValue, IVectorView<Qualifier> qualifiers);
        }

        [interface_name("IResourceCandidate", 0E1518AA-11DC-4B4D-B9BD-0950F7E6CF77)]
        {
            String ResourceName { get; set; };
            ResourceValueType ValueType { get; set; };
            Object Value { get; };
            String StringValue { get; set; };
            UInt8[] DataValue { get; set; };
            IVectorView<Qualifier> Qualifiers { get; set; };

            [default_overload]
            void SetValue(String value);
            [method_name("SetValueWithValueType")]
            void SetValue(ResourceValueType valueType, String value);
            [method_name("SetValueWithDataBytes")]
            void SetValue(UInt8[] value);
        }

        [interface_name("IResourceCandidate2", 159CB3A8-2243-4636-AACE-B262E54E7395)]
        {
            Windows.Storage.Streams.IBuffer DataValueBuffer { get; set; };
            Windows.Storage.Streams.IBuffer DataValueReference { get; };

            [method_name("SetValueWithDataBuffer")]
            void SetValue(Windows.Storage.Streams.IBuffer value);
        }
    }
}